name: Build Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/LicensedPlugins-${{ github.ref_name }}.jar
          body: |
            ## Installation via JitPack

            Add JitPack to your repositories:
            ```xml
            <repositories>
              <repository>
                <id>jitpack.io</id>
                <url>https://jitpack.io</url>
              </repository>
            </repositories>
            ```

            Add the dependency:
            ```xml
            <dependency>
              <groupId>com.github.hubailmn</groupId>
              <artifactId>JDAUtility</artifactId>
              <version>${{ github.ref_name }}</version>
            </dependency>
            ```

            Shade the dependency:
            ```xml
            <build>
              <plugins>
                <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-shade-plugin</artifactId>
                  <version>3.5.0</version>
                  <executions>
                    <execution>
                      <phase>package</phase>
                      <goals>
                        <goal>shade</goal>
                      </goals>
                      <configuration>
                        <createDependencyReducedPom>false</createDependencyReducedPom>
                        <relocations>
                          <relocation>
                            <pattern>me.hubailmn.util</pattern>
                            <shadedPattern>me.hubailmn.shaded.util</shadedPattern>
                          </relocation>
                        </relocations>
                      </configuration>
                    </execution>
                  </executions>
                </plugin>
              </plugins>
            </build>
            ```

            ---
            > **Version**: `${{ github.ref_name }}`
          draft: false
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
